# Generated by Django 3.1.6 on 2021-05-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('types', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
            ],
        ),
    ]
