# Generated by Django 3.1.6 on 2021-05-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_auto_20210518_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_register',
            name='date_of_complaint',
            field=models.DateField(auto_now=True),
        ),
    ]
