# Generated by Django 3.1.6 on 2021-05-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_auto_20210518_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='super_user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('super_user_name', models.CharField(max_length=50)),
                ('passcode', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
