# Generated by Django 3.1.6 on 2021-05-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0006_remove_complaint_register_steps_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_register',
            name='acknowledgement_of_complaint',
        ),
        migrations.RemoveField(
            model_name='complaint_register',
            name='complaint_status',
        ),
        migrations.RemoveField(
            model_name='complaint_register',
            name='date_of_update',
        ),
    ]
