# Generated by Django 3.1.6 on 2021-05-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0007_auto_20210519_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_register',
            name='acknowledgement_of_complaint',
            field=models.CharField(default='Not Applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint_register',
            name='complaint_status',
            field=models.CharField(default='Not Applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint_register',
            name='date_of_update',
            field=models.CharField(default='Not Applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint_register',
            name='steps_taken',
            field=models.CharField(default='Not Applicable', max_length=3000),
        ),
    ]
